#!/usr/bin/env python3
"""Exact-rational, hardware-free RF candidate calculations; not a driver."""

from fractions import Fraction as F
import math

FS = 150_000_000
PLL = 900_000_000
MAX_DEN = (1 << 20) - 1
SPACING = F(12000, 8192)
SYMBOL = 1 / SPACING
# 2 s power check, three 2 s fault jobs, and two sets of tones/transitions/frame.
MEASUREMENT_RF_ON_NS = 8_000_000_000 + 2 * (20_000_000_000 + 10_922_666_667 + 110_592_000_000)
BASES = (3_570_100, 7_040_100, 10_140_200, 14_097_100,
         18_106_100, 21_096_100, 24_926_100, 28_126_100)


def nearest(value):
    """Nearest integer, positive ties upward; all modeled quantities positive."""
    return (2 * value.numerator + value.denominator) // (2 * value.denominator)


def divider(frequency, scale, toggles=1, source=FS):
    ideal = F(source * scale, toggles) / frequency
    low = ideal.numerator // ideal.denominator
    if low < scale:
        raise ValueError("Frequency exceeds modeled divider range")
    word = min((low, low + 1),
               key=lambda n: abs(F(source * scale, toggles * n) - frequency))
    return word, F(source * scale, toggles * word)


def nco(frequency):
    word = nearest(frequency * (1 << 32) / FS)
    return word, F(FS * word, 1 << 32)


def multisynth(frequency):
    ratio = (F(PLL) / frequency).limit_denominator(MAX_DEN)
    if not 8 < ratio < 900:
        raise ValueError("Outside this study's conservative MultiSynth range")
    return ratio, F(PLL) / ratio


def pll_outputs():
    """12 MHz crystal, >=5 MHz reference, legal VCO, <=150 MHz output."""
    values = set()
    for refdiv in (1, 2):
        for feedback in range(16, 321):
            vco = F(12_000_000 * feedback, refdiv)
            if not 750_000_000 <= vco <= 1_600_000_000:
                continue
            for p1 in range(1, 8):
                for p2 in range(1, p1 + 1):
                    rate = vco / (p1 * p2)
                    if rate <= FS:
                        values.add(rate)
    return sorted(values)


def edge_errors(frequency, count=4096):
    """Ideal half-cycle deadlines rounded upward to a 150 MHz sample grid."""
    half = F(FS, 2) / frequency
    errors = []
    for n in range(1, count + 1):
        deadline = n * half
        rounded = -(-deadline.numerator // deadline.denominator)
        errors.append(F(rounded) - deadline)
    return errors


def aliases(word):
    """Odd phase harmonics 3..255 of a full-period NCO MSB, with ZOH.

    Coefficients are analytical discrete Fourier series, not a short FFT.
    Returned levels cover this finite harmonic set, not all possible spurs.
    """
    period = (1 << 32) // math.gcd(word, 1 << 32)
    step = word // math.gcd(word, 1 << 32)
    fundamental = step / period

    def sinc(x):
        return math.sin(math.pi * x) / (math.pi * x) if x else 1.0

    result = []
    for order in range(3, 256, 2):
        index = (order * step) % period
        index = min(index, period - index)
        if index == 0 or index == step:
            continue
        relative = abs(math.sin(math.pi / period) / math.sin(math.pi * order / period))
        relative *= abs(sinc(index / period) / sinc(fundamental))
        result.append((order, F(index * FS, period), 20 * math.log10(relative)))
    return result


def report():
    lines = ["# RF calculation results", "",
             "Generated by `python3 scripts/analyze_rf_feasibility.py`. Ideal clocks;",
             "hardware-free mathematical evidence only. Definitions and limits are in",
             "[RF feasibility](rf-feasibility.md). Frequencies are lowest RF tones, not dial frequencies.", "",
             "## Four-tone error summary", "",
             "Maximum absolute error over tones 0..3, in Hz. PIO and GPOUT use fixed 150 MHz.", "",
             "| Base Hz | PIO 16.8 | GPOUT 16.16 | NCO 32-bit | Si5351 rational |",
             "|---:|---:|---:|---:|---:|"]
    for base in BASES:
        tones = [F(base) + t * SPACING for t in range(4)]
        errors = [max(abs(fn(f)[1] - f) for f in tones) for fn in
                  (lambda f: divider(f, 256, 2), lambda f: divider(f, 65536), nco, multisynth)]
        lines.append(f"| {base} | " + " | ".join(f"{float(e):.9f}" for e in errors) + " |")
    lines += ["", "## Exact tone plans", "",
              "PIO/GPOUT integers encode their full scaled divider; NCO integer is the phase increment.",
              "Si5351 ratio is the complete MultiSynth divisor, with fixed 900 MHz PLL and R=1.",
              "Actual Hz can be recovered exactly from these integers and the documented formulas.", "",
              "| Base Hz | Tone | PIO word | GPOUT word | NCO word | Si5351 divisor |",
              "|---:|---:|---:|---:|---:|---:|"]
    for base in BASES:
        for tone in range(4):
            f = F(base) + tone * SPACING
            lines.append(f"| {base} | {tone} | {divider(f, 256, 2)[0]} | "
                         f"{divider(f, 65536)[0]} | {nco(f)[0]} | {multisynth(f)[0]} |")
    rates = pll_outputs()
    lines += ["", "## Retuned PLL plus GPOUT search", "",
              "Optimistic per-tone search over legal PLL outputs <=150 MHz from a 12 MHz crystal,",
              "then a 16.16 GPOUT divider. This permits changing the parent at every tone;",
              "it does not establish a usable USB/system clock tree or phase-continuous retuning.", "",
              "| Base Hz | Maximum error Hz |",
              "|---:|---:|"]
    for base in BASES:
        error = max(min(abs(divider(F(base) + t * SPACING, 65536, source=rate)[1]
                                - (F(base) + t * SPACING))
                            for rate in rates if rate >= F(base) + t * SPACING)
                    for t in range(4))
        lines.append(f"| {base} | {float(error):.9f} |")
    lines += ["", "## Direct stream phase and spectral model", "",
              "Tone 0 of each base; 4096 rounded half-cycle deadlines. Peak is sample-grid error",
              "relative to the represented NCO frequency, excluding its mean tuning error.",
              "The spectral entry is the strongest folded component among odd orders 3..255,",
              "including sample-and-hold response. It is not a measured or complete spur bound.", "",
              "| Base Hz | Peak edge error ns | NCO period s | Order | Folded MHz | Model dBc | Strongest below-carrier order / MHz / dBc |",
              "|---:|---:|---:|---:|---:|---:|---:|"]
    for base in BASES:
        word, actual = nco(F(base))
        peak = max(edge_errors(actual)) * F(1_000_000_000, FS)
        period = F((1 << 32) // math.gcd(word, 1 << 32), FS)
        components = aliases(word)
        order, frequency, level = max(components, key=lambda entry: entry[2])
        below = max((entry for entry in components if entry[1] < actual), key=lambda entry: entry[2])
        lines.append(f"| {base} | {float(peak):.6f} | {float(period):.9f} | {order} | "
                     f"{float(frequency / 1_000_000):.6f} | {level:.3f} | "
                     f"{below[0]} / {float(below[1] / 1_000_000):.6f} / {below[2]:.3f} |")
    lines += ["", "## Timing and storage", "",
              f"- Exact symbol duration: {SYMBOL} s; 162 symbols: {162 * SYMBOL} s.",
              f"- 150 MHz clocks per symbol: {FS * SYMBOL}; packed bytes per frame: {FS * SYMBOL * 162 / 8}.",
              f"- Packed one-bit stream: {FS // 8} bytes/s; 64 KiB half-buffer: {65536 / (FS / 8):.9f} s.",
              "- Absolute nearest-microsecond deadlines have <=0.5 us error; frame-end error is zero.",
              "- Repeating a rounded 682667 us interval accumulates 54 us over 162 symbols.",
              f"- Proposed measurement sequence RF-on upper budget: {MEASUREMENT_RF_ON_NS} ns.", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    print(report(), end="")
