set(WSPRRY_PICO_TEST_MBEDTLS_PATH "" CACHE PATH "Optional pinned local Mbed TLS for actual TLS host tests")
if(WSPRRY_PICO_TEST_MBEDTLS_PATH)
    enable_language(C)
    execute_process(COMMAND git -C "${WSPRRY_PICO_TEST_MBEDTLS_PATH}" rev-parse HEAD
        OUTPUT_VARIABLE tls_revision OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE tls_result)
    if(NOT tls_result EQUAL 0 OR NOT tls_revision STREQUAL "0bebf8b8c7f07abe3571ded48a11aa907a1ffb20")
        message(FATAL_ERROR "TLS tests require the SDK-pinned Mbed TLS revision")
    endif()
    execute_process(COMMAND git -C "${WSPRRY_PICO_TEST_MBEDTLS_PATH}" status --porcelain --untracked-files=no
        OUTPUT_VARIABLE tls_status OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE tls_status_result)
    if(NOT tls_status_result EQUAL 0 OR NOT tls_status STREQUAL "")
        message(FATAL_ERROR "TLS tests require an unmodified pinned Mbed TLS checkout")
    endif()
    set(MBEDTLS_DIR ${WSPRRY_PICO_TEST_MBEDTLS_PATH})
    set(MBEDTLS_CONFIG_FILE "${CMAKE_SOURCE_DIR}/src/network/pico/mbedtls_config.h")
    set(GEN_FILES OFF)
    set(USE_STATIC_MBEDTLS_LIBRARY ON)
    set(USE_SHARED_MBEDTLS_LIBRARY OFF)
    set(DISABLE_PACKAGE_CONFIG_AND_INSTALL ON)
    add_subdirectory(${WSPRRY_PICO_TEST_MBEDTLS_PATH}/library ${CMAKE_BINARY_DIR}/mbedtls)
    set(WSPRRY_PICO_TEST_CREDENTIAL_DIR "${CMAKE_BINARY_DIR}/network-test-credentials")
    if(NOT EXISTS "${WSPRRY_PICO_TEST_CREDENTIAL_DIR}/server.key")
        execute_process(COMMAND ${Python3_EXECUTABLE} ${CMAKE_SOURCE_DIR}/scripts/generate_network_test_credentials.py
            "${WSPRRY_PICO_TEST_CREDENTIAL_DIR}" COMMAND_ERROR_IS_FATAL ANY)
    endif()
    set(WSPRRY_PICO_NETWORK_PORT 18443)
    file(READ "${WSPRRY_PICO_TEST_CREDENTIAL_DIR}/server.crt" WSPRRY_PICO_CERTIFICATE)
    file(READ "${WSPRRY_PICO_TEST_CREDENTIAL_DIR}/server.key" WSPRRY_PICO_PRIVATE_KEY)
    file(READ "${WSPRRY_PICO_TEST_CREDENTIAL_DIR}/client-ca.crt" WSPRRY_PICO_CLIENT_CA)
    configure_file(${CMAKE_SOURCE_DIR}/cmake/network_credentials.hpp.in
                   ${CMAKE_BINARY_DIR}/network-test-generated/network_credentials.hpp @ONLY)
    file(CHMOD ${CMAKE_BINARY_DIR}/network-test-generated/network_credentials.hpp PERMISSIONS OWNER_READ OWNER_WRITE)
    add_executable(network_tls_driver tests/network_tls_driver.cpp tests/network_mock/tcp.cpp src/network/pico/server.cpp)
    target_include_directories(network_tls_driver PRIVATE tests/network_mock ${CMAKE_BINARY_DIR}/network-test-generated)
    target_compile_definitions(network_tls_driver PRIVATE MBEDTLS_CONFIG_FILE="${MBEDTLS_CONFIG_FILE}")
    target_link_libraries(network_tls_driver PRIVATE wsprrypico_core wsprrypico_rf Threads::Threads mbedtls mbedx509 mbedcrypto)
    target_compile_options(network_tls_driver PRIVATE -Wall -Wextra -Wpedantic -Werror)
    add_test(NAME network_tls_tests COMMAND ${Python3_EXECUTABLE} ${CMAKE_SOURCE_DIR}/tests/network_tls_tests.py
        $<TARGET_FILE:network_tls_driver> ${WSPRRY_PICO_TEST_CREDENTIAL_DIR})
    set_tests_properties(network_tls_tests PROPERTIES TIMEOUT 90 RUN_SERIAL TRUE)
endif()

include(${CMAKE_SOURCE_DIR}/cmake/network_client_interop.cmake)
